### ISSUE TITLE
login/password for dev site?

### ISSUE THREAD

**Issue by vfulco** [t04glovern/kitty-catalog#1]
Wanted to checkout layout as I may like for another domain application.  TIA.

**Comment by t04glovern** [comment]
Hey @vfulco,
This app is more or less a copy of the one you build in the https://serverless-stack.com/ tutorial. I believe I've since destroyed the Cognito provider behind this repo.

I would recommend checking out the serverless stack tutorial as its free and more or less a mirror of this repo (just without cats haha)

**Comment by vfulco** [comment]
That's great to know and was on my list.  Thanks again.
